#SELECT ANIMAL_ID, NAME 
#FROM ANIMAL_INS
#WHERE ANIMAL_TYPE = 'DOG' AND UPPER(NAME) LIKE '%EL%'
#ORDER BY NAME;

SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT * 
      FROM ANIMAL_INS
      WHERE ANIMAL_TYPE = 'DOG') AS A
WHERE UPPER(A.NAME) LIKE '%EL%'
ORDER BY A.NAME;