# SELECT COUNT(USER_ID) as USERS
# FROM USER_INFO 
# WHERE LEFT(JOINED, 4) = 2021 AND 20 <= AGE <= 29;

SELECT COUNT(USER_ID) as USERS
FROM USER_INFO 
WHERE LEFT(JOINED, 4) = 2021 AND 20 <= AGE AND AGE <= 29;