### CASE 1 : IFNULL
#SELECT  WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') 
#FROM FOOD_WAREHOUSE
#WHERE ADDRESS LIKE '경기도%';
#ORDER BY WAREHOUSE_ID

### CASE 2 : COALESCE
#SELECT  WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') 
#FROM FOOD_WAREHOUSE
#WHERE ADDRESS LIKE '경기도%';
#ORDER BY WAREHOUSE_ID

### CASE 3 : IF문
SELECT  WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IF(FREEZER_YN IS NULL, 'N', FREEZER_YN) 
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;