# SELECT CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
# FROM BOOK
# LEFT JOIN (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS TOTAL_SALES
#       FROM BOOK_SALES
#       GROUP BY BOOK_ID
#       HAVING DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') AS BOOK_SALES
# ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
# GROUP BY CATEGORY
# ORDER BY CATEGORY ASC;

SELECT BOOK.CATEGORY,  SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK 
LEFT JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE LEFT(BOOK_SALES.SALES_DATE, 7) = '2022-01'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY;